package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.OauthCode;

public interface OauthCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    int insert(OauthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    int insertSelective(OauthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    OauthCode selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    int updateByPrimaryKeySelective(OauthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    int updateByPrimaryKeyWithBLOBs(OauthCode record);
}