package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.OauthAccessToken;

public interface OauthAccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    int deleteByPrimaryKey(String tokenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    int insert(OauthAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    int insertSelective(OauthAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    OauthAccessToken selectByPrimaryKey(String tokenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    int updateByPrimaryKeySelective(OauthAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    int updateByPrimaryKeyWithBLOBs(OauthAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    int updateByPrimaryKey(OauthAccessToken record);
}