package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.PkOauthCode;

public interface PkOauthCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_oauth_code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    int insert(PkOauthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_oauth_code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    int insertSelective(PkOauthCode record);
}