package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.PkOauthRefreshToken;

public interface PkOauthRefreshTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_oauth_refresh_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    int insert(PkOauthRefreshToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_oauth_refresh_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    int insertSelective(PkOauthRefreshToken record);
}