/*
 * Copyright (C) 2014 STNet,Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package com.mycompany.apps.domain.mappers;

import com.mycompany.apps.domain.entities.Users;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table public.users
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("username") String username);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table public.users
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table public.users
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table public.users
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    Users selectByPrimaryKey(@Param("id") Integer id, @Param("username") String username);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table public.users
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    int updateByPrimaryKeySelective(Users record);

    Users selectByUsername(@Param("username") String username);

    List<Users> findAllUsers();

    List<String> hasRoles(@Param("username") String username);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table public.users
     *
     * @mbggenerated Tue Jun 17 18:24:33 JST 2014
     */
    int updateByPrimaryKey(Users record);
}
