package com.mycompany.apps.domain.entities;

public class OauthCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_code.code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_code.authentication
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    private byte[] authentication;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.oauth_code.code
     *
     * @return the value of public.oauth_code.code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.oauth_code.code
     *
     * @param code the value for public.oauth_code.code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.oauth_code.authentication
     *
     * @return the value of public.oauth_code.authentication
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public byte[] getAuthentication() {
        return authentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.oauth_code.authentication
     *
     * @param authentication the value for public.oauth_code.authentication
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public void setAuthentication(byte[] authentication) {
        this.authentication = authentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OauthCode other = (OauthCode) that;
        return (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getAuthentication() == null ? other.getAuthentication() == null : this.getAuthentication().equals(other.getAuthentication()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getAuthentication() == null) ? 0 : getAuthentication().hashCode());
        return result;
    }
}