package com.mycompany.apps.domain.entities;

public class OauthRefreshToken {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_refresh_token.token_id
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    private String tokenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_refresh_token.token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    private byte[] token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_refresh_token.authentication
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    private byte[] authentication;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.oauth_refresh_token.token_id
     *
     * @return the value of public.oauth_refresh_token.token_id
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public String getTokenId() {
        return tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.oauth_refresh_token.token_id
     *
     * @param tokenId the value for public.oauth_refresh_token.token_id
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public void setTokenId(String tokenId) {
        this.tokenId = tokenId == null ? null : tokenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.oauth_refresh_token.token
     *
     * @return the value of public.oauth_refresh_token.token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public byte[] getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.oauth_refresh_token.token
     *
     * @param token the value for public.oauth_refresh_token.token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public void setToken(byte[] token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.oauth_refresh_token.authentication
     *
     * @return the value of public.oauth_refresh_token.authentication
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public byte[] getAuthentication() {
        return authentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.oauth_refresh_token.authentication
     *
     * @param authentication the value for public.oauth_refresh_token.authentication
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public void setAuthentication(byte[] authentication) {
        this.authentication = authentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_refresh_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OauthRefreshToken other = (OauthRefreshToken) that;
        return (this.getTokenId() == null ? other.getTokenId() == null : this.getTokenId().equals(other.getTokenId()))
            && (this.getToken() == null ? other.getToken() == null : this.getToken().equals(other.getToken()))
            && (this.getAuthentication() == null ? other.getAuthentication() == null : this.getAuthentication().equals(other.getAuthentication()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_refresh_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTokenId() == null) ? 0 : getTokenId().hashCode());
        result = prime * result + ((getToken() == null) ? 0 : getToken().hashCode());
        result = prime * result + ((getAuthentication() == null) ? 0 : getAuthentication().hashCode());
        return result;
    }
}