/*
 * Copyright (C) 2014 STNet,Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package com.mycompany.apps.domain.entities;

public class OauthAccessToken {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_access_token.token_id
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    private String tokenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_access_token.authentication_id
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    private String authenticationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_access_token.user_name
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_access_token.client_id
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_access_token.refresh_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    private String refreshToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_access_token.token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    private byte[] token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.oauth_access_token.authentication
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    private byte[] authentication;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.oauth_access_token.token_id
     *
     * @return the value of public.oauth_access_token.token_id
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public String getTokenId() {
        return tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.oauth_access_token.token_id
     *
     * @param tokenId the value for public.oauth_access_token.token_id
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public void setTokenId(String tokenId) {
        this.tokenId = tokenId == null ? null : tokenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.oauth_access_token.authentication_id
     *
     * @return the value of public.oauth_access_token.authentication_id
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public String getAuthenticationId() {
        return authenticationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.oauth_access_token.authentication_id
     *
     * @param authenticationId the value for public.oauth_access_token.authentication_id
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public void setAuthenticationId(String authenticationId) {
        this.authenticationId = authenticationId == null ? null : authenticationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.oauth_access_token.user_name
     *
     * @return the value of public.oauth_access_token.user_name
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.oauth_access_token.user_name
     *
     * @param userName the value for public.oauth_access_token.user_name
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.oauth_access_token.client_id
     *
     * @return the value of public.oauth_access_token.client_id
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.oauth_access_token.client_id
     *
     * @param clientId the value for public.oauth_access_token.client_id
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.oauth_access_token.refresh_token
     *
     * @return the value of public.oauth_access_token.refresh_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.oauth_access_token.refresh_token
     *
     * @param refreshToken the value for public.oauth_access_token.refresh_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken == null ? null : refreshToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.oauth_access_token.token
     *
     * @return the value of public.oauth_access_token.token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public byte[] getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.oauth_access_token.token
     *
     * @param token the value for public.oauth_access_token.token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public void setToken(byte[] token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.oauth_access_token.authentication
     *
     * @return the value of public.oauth_access_token.authentication
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public byte[] getAuthentication() {
        return authentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.oauth_access_token.authentication
     *
     * @param authentication the value for public.oauth_access_token.authentication
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public void setAuthentication(byte[] authentication) {
        this.authentication = authentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OauthAccessToken other = (OauthAccessToken) that;
        return (this.getTokenId() == null ? other.getTokenId() == null : this.getTokenId().equals(other.getTokenId()))
            && (this.getAuthenticationId() == null ? other.getAuthenticationId() == null : this.getAuthenticationId().equals(other.getAuthenticationId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getClientId() == null ? other.getClientId() == null : this.getClientId().equals(other.getClientId()))
            && (this.getRefreshToken() == null ? other.getRefreshToken() == null : this.getRefreshToken().equals(other.getRefreshToken()))
            && (this.getToken() == null ? other.getToken() == null : this.getToken().equals(other.getToken()))
            && (this.getAuthentication() == null ? other.getAuthentication() == null : this.getAuthentication().equals(other.getAuthentication()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.oauth_access_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTokenId() == null) ? 0 : getTokenId().hashCode());
        result = prime * result + ((getAuthenticationId() == null) ? 0 : getAuthenticationId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getClientId() == null) ? 0 : getClientId().hashCode());
        result = prime * result + ((getRefreshToken() == null) ? 0 : getRefreshToken().hashCode());
        result = prime * result + ((getToken() == null) ? 0 : getToken().hashCode());
        result = prime * result + ((getAuthentication() == null) ? 0 : getAuthentication().hashCode());
        return result;
    }
}