package com.mycompany.apps.domain.entities;

public class PkOauthAccessToken {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pk_oauth_access_token.token_id
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    private String tokenId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pk_oauth_access_token.token_id
     *
     * @return the value of public.pk_oauth_access_token.token_id
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public String getTokenId() {
        return tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pk_oauth_access_token.token_id
     *
     * @param tokenId the value for public.pk_oauth_access_token.token_id
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public void setTokenId(String tokenId) {
        this.tokenId = tokenId == null ? null : tokenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_oauth_access_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PkOauthAccessToken other = (PkOauthAccessToken) that;
        return (this.getTokenId() == null ? other.getTokenId() == null : this.getTokenId().equals(other.getTokenId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_oauth_access_token
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTokenId() == null) ? 0 : getTokenId().hashCode());
        return result;
    }
}