package com.mycompany.apps.domain.entities;

public class PkOauthCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pk_oauth_code.code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pk_oauth_code.code
     *
     * @return the value of public.pk_oauth_code.code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pk_oauth_code.code
     *
     * @param code the value for public.pk_oauth_code.code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_oauth_code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PkOauthCode other = (PkOauthCode) that;
        return (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pk_oauth_code
     *
     * @mbggenerated Sat Jun 21 20:18:08 JST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        return result;
    }
}